version: '3.7'
services:
  vault-server:
    container_name: vault-server
    hostname: vault-server
    image: vault:latest
    command: ["server", "-dev"]
    ports: 
      - 8200:8200
    networks:
      - test-net
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=qwerty
      - VAULT_LOG_LEVEL=trace
    restart: always
  quorum:
    container_name: quorum
    hostname:  quorum
    build:
      context: ./images/
      dockerfile: Dockerfile
    image: fullkomnun/quorum-hashicorp-plugin:1.0.0
    volumes:
      - ./scripts/entry.sh:/entry.sh:ro
      - ./datadir/genesis.json:/qdata/dd/genesis.json:ro
      #- ./datadir/nodekey:/qdata/dd/nodekey
      #- ./datadir/static-nodes.json:/qdata/dd/static-nodes.json
    entrypoint: /entry.sh
    ports: 
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
      - 50400:50400    
    depends_on:
      - vault-server
    networks:
      - test-net
    environment:
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=raft
      - VAULT_DEV_ROOT_TOKEN_ID=qwerty
    #restart: always
networks:
  test-net:
    driver: bridge
    ipam:
      driver: default