version: '3.7'
services:
  quorum:
    container_name: quorum
    build:
      context: ./images/
      dockerfile: Dockerfile
    image: fullkomnun/quorum-helloworld-plugin:1.0.0
    volumes:
      - ./scripts/entry.sh:/entry.sh:ro
      - ./datadir/genesis.json:/qdata/dd/genesis.json:ro
      #- ./datadir/nodekey:/qdata/dd/nodekey
      #- ./datadir/static-nodes.json:/qdata/dd/static-nodes.json
    entrypoint: /entry.sh
    ports: 
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
      - 50400:50400
    environment:
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=raft
    restart: always